//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_topicos
    {
        public tb_IntDek_cd_topicos()
        {
            this.tb_IntDek_cd_topicos_img = new HashSet<tb_IntDek_cd_topicos_img>();
        }
    
        public int cod_topico { get; set; }
        public int cod_cap { get; set; }
        public string titulo { get; set; }
        public string conteudo_principal { get; set; }
        public string conteudo_secundario { get; set; }
    
        public virtual tb_IntDek_cd_cap_cursos tb_IntDek_cd_cap_cursos { get; set; }
        public virtual ICollection<tb_IntDek_cd_topicos_img> tb_IntDek_cd_topicos_img { get; set; }
    }
}
