//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_exercicios
    {
        public tb_IntDek_cd_exercicios()
        {
            this.tb_IntDek_cd_alterantivas = new HashSet<tb_IntDek_cd_alterantivas>();
        }
    
        public int cod_exercicio { get; set; }
        public Nullable<int> cod_cap { get; set; }
        public string pergunta { get; set; }
        public bool pergunta_chave { get; set; }
        public byte[] img { get; set; }
    
        public virtual ICollection<tb_IntDek_cd_alterantivas> tb_IntDek_cd_alterantivas { get; set; }
        public virtual tb_IntDek_cd_cap_cursos tb_IntDek_cd_cap_cursos { get; set; }
    }
}
