//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_usuarios
    {
        public tb_IntDek_cd_usuarios()
        {
            this.tb_IntDek_cd_cursos_andamento = new HashSet<tb_IntDek_cd_cursos_andamento>();
            this.tb_IntDek_cd_cursos_realizados = new HashSet<tb_IntDek_cd_cursos_realizados>();
        }
    
        public int cod_usuario { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
    
        public virtual ICollection<tb_IntDek_cd_cursos_andamento> tb_IntDek_cd_cursos_andamento { get; set; }
        public virtual ICollection<tb_IntDek_cd_cursos_realizados> tb_IntDek_cd_cursos_realizados { get; set; }
    }
}
