//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_cursos
    {
        public tb_IntDek_cd_cursos()
        {
            this.tb_IntDek_cd_cap_cursos = new HashSet<tb_IntDek_cd_cap_cursos>();
            this.tb_IntDek_cd_cursos_andamento = new HashSet<tb_IntDek_cd_cursos_andamento>();
            this.tb_IntDek_cd_cursos_realizados = new HashSet<tb_IntDek_cd_cursos_realizados>();
        }
    
        public int cod_curso { get; set; }
        public string titulo { get; set; }
        public System.DateTime data_criacao { get; set; }
        public string obs_mercado { get; set; }
        public string descricao { get; set; }
        public int cod_class { get; set; }
    
        public virtual ICollection<tb_IntDek_cd_cap_cursos> tb_IntDek_cd_cap_cursos { get; set; }
        public virtual tb_IntDek_cd_class_cursos tb_IntDek_cd_class_cursos { get; set; }
        public virtual ICollection<tb_IntDek_cd_cursos_andamento> tb_IntDek_cd_cursos_andamento { get; set; }
        public virtual ICollection<tb_IntDek_cd_cursos_realizados> tb_IntDek_cd_cursos_realizados { get; set; }
    }
}
