//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_topicos_img
    {
        public int cod_img { get; set; }
        public Nullable<int> cod_topico { get; set; }
        public string descricao { get; set; }
        public byte[] img { get; set; }
    
        public virtual tb_IntDek_cd_topicos tb_IntDek_cd_topicos { get; set; }
    }
}
