//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_alterantivas
    {
        public int cod_alternativa { get; set; }
        public Nullable<int> cod_exercicio { get; set; }
        public string conteudo { get; set; }
        public bool certa { get; set; }
    
        public virtual tb_IntDek_cd_exercicios tb_IntDek_cd_exercicios { get; set; }
    }
}
