//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_cursos_andamento
    {
        public int cod_cap { get; set; }
        public int cod_usuario { get; set; }
        public int cod_curso { get; set; }
        public bool posicao { get; set; }
        public int acertos { get; set; }
        public bool aprovado { get; set; }
    
        public virtual tb_IntDek_cd_cap_cursos tb_IntDek_cd_cap_cursos { get; set; }
        public virtual tb_IntDek_cd_cursos tb_IntDek_cd_cursos { get; set; }
        public virtual tb_IntDek_cd_usuarios tb_IntDek_cd_usuarios { get; set; }
    }
}
