//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_class_cursos
    {
        public tb_IntDek_cd_class_cursos()
        {
            this.tb_IntDek_cd_cursos = new HashSet<tb_IntDek_cd_cursos>();
        }
    
        public int cod_class { get; set; }
        public string descricao { get; set; }
        public string obs_mercado { get; set; }
    
        public virtual ICollection<tb_IntDek_cd_cursos> tb_IntDek_cd_cursos { get; set; }
    }
}
