//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Integradesk_dbEntities : DbContext
    {
        public Integradesk_dbEntities()
            : base("name=Integradesk_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_IntDek_cd_alterantivas> tb_IntDek_cd_alterantivas { get; set; }
        public virtual DbSet<tb_IntDek_cd_cap_cursos> tb_IntDek_cd_cap_cursos { get; set; }
        public virtual DbSet<tb_IntDek_cd_class_cursos> tb_IntDek_cd_class_cursos { get; set; }
        public virtual DbSet<tb_IntDek_cd_cursos> tb_IntDek_cd_cursos { get; set; }
        public virtual DbSet<tb_IntDek_cd_cursos_andamento> tb_IntDek_cd_cursos_andamento { get; set; }
        public virtual DbSet<tb_IntDek_cd_cursos_realizados> tb_IntDek_cd_cursos_realizados { get; set; }
        public virtual DbSet<tb_IntDek_cd_exercicios> tb_IntDek_cd_exercicios { get; set; }
        public virtual DbSet<tb_IntDek_cd_topicos> tb_IntDek_cd_topicos { get; set; }
        public virtual DbSet<tb_IntDek_cd_topicos_img> tb_IntDek_cd_topicos_img { get; set; }
        public virtual DbSet<tb_IntDek_cd_usuarios> tb_IntDek_cd_usuarios { get; set; }
    }
}
