//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegraDesk.Charging
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IntDek_cd_cap_cursos
    {
        public tb_IntDek_cd_cap_cursos()
        {
            this.tb_IntDek_cd_cursos_andamento = new HashSet<tb_IntDek_cd_cursos_andamento>();
            this.tb_IntDek_cd_exercicios = new HashSet<tb_IntDek_cd_exercicios>();
            this.tb_IntDek_cd_topicos = new HashSet<tb_IntDek_cd_topicos>();
        }
    
        public int cod_cap { get; set; }
        public Nullable<int> cod_curso { get; set; }
        public int duracao { get; set; }
        public string titulo { get; set; }
    
        public virtual tb_IntDek_cd_cursos tb_IntDek_cd_cursos { get; set; }
        public virtual ICollection<tb_IntDek_cd_cursos_andamento> tb_IntDek_cd_cursos_andamento { get; set; }
        public virtual ICollection<tb_IntDek_cd_exercicios> tb_IntDek_cd_exercicios { get; set; }
        public virtual ICollection<tb_IntDek_cd_topicos> tb_IntDek_cd_topicos { get; set; }
    }
}
